name: Build and Upload Development Bot Image to GHCR

on:
  push:
    branches:
      - dev
    paths:
      - python_app/**
  workflow_dispatch:

jobs:
  publish-php-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Build the dashboard docker image
        run: |
          version=$(cat dashboard/Dockerfile | grep 'ENV PHP_VERSION' | awk '{print $3}' | sed -e 's/\./-/g')
          revision=$(git rev-parse --short ${{ github.sha }})
          docker build python_app --tag ghcr.io/tuaathadedanann/images/bot-$version-dev:$revision
          docker tag ghcr.io/tuaathadedanann/images/bot-$version-dev:$revision ghcr.io/tuaathadedanann/images/bot-dev:latest
          docker push ghcr.io/tuaathadedanann/images/bot-$version-dev:$revision
          docker push ghcr.io/tuaathadedanann/images/bot-dev:latest